### ISSUE TITLE
Doesn't show data from CSV and MySQL

### ISSUE THREAD

**Issue by Suleman-Elahi** [cube2222/octosql#117]
In my case, I am trying to join data from a CSV and MySQL source. But in the end, it shows nothing in the output.

Platform: Windows, 64 Bit

![image](https://user-images.githubusercontent.com/24384996/61375245-01430c00-a8bc-11e9-9c85-e6ea509dc830.png)

**Comment by cube2222** [comment]
Hey, you have a typo there, you aliased the table cut with c, but later used cut.asin :)

**Comment by Suleman-Elahi** [comment]
Oh, I was just experimenting with that. However, it still doesn't work. But if you use table name directly in ON then it does shows something.

![image](https://user-images.githubusercontent.com/24384996/61428868-9fc58080-a941-11e9-80b9-7889fdb43190.png)

**Comment by cube2222** [comment]
Would it be possible for you to post a describe of your MySQL table? I think it has something to do with types not matching. (I'll make sure to add some helper functions to view type information)

**Comment by Suleman-Elahi** [comment]
Here it is.
![Uploading image.png…]()

**Comment by cube2222** [comment]
Hey, looking at your last image you use c.id (even though above it was c.asin). I failed to reproduce your issue.

With a csv table:
```
asin,name
1,test
2,test2
3,test3
```

And mysql table (int, text, text):
```
1	testt	test@test
2	testt2	test2@test
3	testt3	test3@test
4	testt4	test4@test
```

an octosql.yaml:
```
dataSources:
  - name: people
    type: mysql
    config:
      address: "localhost:3306"
      user: root
      password: toor
      databaseName: app
      tableName: people
  - name: cut
    type: csv
    config:
      path: "cut.csv"
```

and invocation:
```
octosql "SELECT p.email, c.name from cut c JOIN people p ON p.id = c.asin"
```

I get:
```
+--------------+---------+
|   p.email    | c.name  |
+--------------+---------+
| 'test@test'  | 'test'  |
| 'test2@test' | 'test2' |
| 'test3@test' | 'test3' |
+--------------+---------+
```

So you'd have to provide all the files / a docker image with a database with data already included for me to help.

**Comment by Suleman-Elahi** [comment]
I don't know what I am doing wrong. Let me try it on Linux and MAC and then I will let you know. I am just in the first year of college so I not confident about it but if it is working fine for you then you can close this issue.

![image](https://user-images.githubusercontent.com/24384996/61509226-33af4f00-aa0b-11e9-92a2-8fecba9e8adb.png)

The octosql.yaml in my case:

```
dataSources:
  - name: cut
    type: csv
    config:
      path: "E:/cust.csv"
  - name: people
    type: mysql
    config:
      address: "localhost:3306"
      user: "root"
      password: "mysql"
      databaseName: "test"
      tableName: "people"
```
