### ISSUE TITLE
[bug] select cannot emit result for cvs 

### ISSUE THREAD

**Issue by acekingke** [cube2222/octosql#263]
the data file is 
```shell
➜  data cat cats.csv
"Id","Sex","Bwt","Hwt"
"1","F",2,7
"2","F",2,7.4
"3","F",2,9.5
"4","F",2.1,7.2
"5","F",2.1,7.3
"7","F",2.1,8.1
"8","F",2.1,8.2
```
The config yaml file is :
```yaml
dataSources:
  - name: cats
    type: csv
    config:
      path: "~/data/cats.csv"
```
run the cmd it like that:
```shell
➜  octosql git:(master) ✗ go run cmd/octosql/*go "select c.* from cats c" -c ~/octosql/octosql.yml
+
+
watermark: 0001-01-01T00:00:00Z
```
