### ISSUE TITLE
couldn't get table from plugin when connect to postgres (private cloud provider)

### ISSUE THREAD

**Issue by swuecho** [cube2222/octosql#292]
Error: typecheck error: couldn't create datasource: couldn't get table from plugin: rpc error: code = Unknown desc = couldn't get table: `schema` configuration setting is required.

I could connect to the postgres instance using psql.

**Comment by swuecho** [comment]
```
databases:
  - name: mydb
    type: postgres
    config:
      host: localhost
      port: 5443
      database: mydb
      user: postgres
      password: postgres
```
add:
     schema: public 

problem solved.
